### ISSUE TITLE
The tag version for LLVM6 is wrong

### ISSUE THREAD

**Issue by Gnimuc** [JuliaBinaryWrappers/LLVM_jll.jl#1]
It looks like the old tag version failed to be overwritten: https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/tree/LLVM-v6.0.1%2B0.

**Comment by vchuravy** [comment]
This is apparently an issue with JLL packages in general @staticfloat the tag is for the commit before the actual commit that ends up in the registry.

**Comment by giordano** [comment]
Yes, the tag never matches the commit of a release, because the tarballs are uploaded to the release (and thus the release is created) before the commit is even created

**Comment by Gnimuc** [comment]
OK, that makes sense to me.
