### ISSUE TITLE
Don't bundle lib/*.a files

### ISSUE THREAD

**Issue by krrutkow** [JuliaBinaryWrappers/LLVM_jll.jl#4]
For Linux builds at very least, the static libraries shouldn't be needed or even usable from Julia, and they add a _substantial_ amount of overhead to the package (310MB).

**Comment by giordano** [comment]
Related, making basically the opposite request, for another package: https://github.com/JuliaBinaryWrappers/Clang_jll.jl/issues/1

**Comment by vchuravy** [comment]
Let's continue this discussion in one place over at Yggdrasil.
